
package fr.doranco.jaxws.soap.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CoursService", targetNamespace = "http://service.jaxws.doranco.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoursService {


    /**
     * 
     * @param arg0
     * @return
     *     returns fr.doranco.jaxws.soap.service.Cours
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCoursById", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.GetCoursById")
    @ResponseWrapper(localName = "getCoursByIdResponse", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.GetCoursByIdResponse")
    @Action(input = "http://service.jaxws.doranco.fr/CoursService/getCoursByIdRequest", output = "http://service.jaxws.doranco.fr/CoursService/getCoursByIdResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.jaxws.doranco.fr/CoursService/getCoursById/Fault/Exception")
    })
    public Cours getCoursById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns fr.doranco.jaxws.soap.service.Cours
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCours", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.AddCours")
    @ResponseWrapper(localName = "addCoursResponse", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.AddCoursResponse")
    @Action(input = "http://service.jaxws.doranco.fr/CoursService/addCoursRequest", output = "http://service.jaxws.doranco.fr/CoursService/addCoursResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.jaxws.doranco.fr/CoursService/addCours/Fault/Exception")
    })
    public Cours addCours(
        @WebParam(name = "arg0", targetNamespace = "")
        Cours arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<fr.doranco.jaxws.soap.service.Cours>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCours", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.GetCours")
    @ResponseWrapper(localName = "getCoursResponse", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.GetCoursResponse")
    @Action(input = "http://service.jaxws.doranco.fr/CoursService/getCoursRequest", output = "http://service.jaxws.doranco.fr/CoursService/getCoursResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.jaxws.doranco.fr/CoursService/getCours/Fault/Exception")
    })
    public List<Cours> getCours()
        throws Exception_Exception
    ;

}
