
package fr.doranco.jaxws.soap.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CoursService", targetNamespace = "http://service.jaxws.doranco.fr/", wsdlLocation = "http://localhost:9991/ws/soap/cours-service?wsdl")
public class CoursService_Service
    extends Service
{

    private final static URL COURSSERVICE_WSDL_LOCATION;
    private final static WebServiceException COURSSERVICE_EXCEPTION;
    private final static QName COURSSERVICE_QNAME = new QName("http://service.jaxws.doranco.fr/", "CoursService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9991/ws/soap/cours-service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURSSERVICE_WSDL_LOCATION = url;
        COURSSERVICE_EXCEPTION = e;
    }

    public CoursService_Service() {
        super(__getWsdlLocation(), COURSSERVICE_QNAME);
    }

    public CoursService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURSSERVICE_QNAME, features);
    }

    public CoursService_Service(URL wsdlLocation) {
        super(wsdlLocation, COURSSERVICE_QNAME);
    }

    public CoursService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURSSERVICE_QNAME, features);
    }

    public CoursService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoursService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CoursService
     */
    @WebEndpoint(name = "CoursPort")
    public CoursService getCoursPort() {
        return super.getPort(new QName("http://service.jaxws.doranco.fr/", "CoursPort"), CoursService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoursService
     */
    @WebEndpoint(name = "CoursPort")
    public CoursService getCoursPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jaxws.doranco.fr/", "CoursPort"), CoursService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURSSERVICE_EXCEPTION!= null) {
            throw COURSSERVICE_EXCEPTION;
        }
        return COURSSERVICE_WSDL_LOCATION;
    }

}
