
package fr.doranco.jaxws.soap.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EtudiantService", targetNamespace = "http://service.jaxws.doranco.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EtudiantService {


    /**
     * 
     * @return
     *     returns java.util.List<fr.doranco.jaxws.soap.service.Etudiant>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtudiants", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.GetEtudiants")
    @ResponseWrapper(localName = "getEtudiantsResponse", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.GetEtudiantsResponse")
    @Action(input = "http://service.jaxws.doranco.fr/EtudiantService/getEtudiantsRequest", output = "http://service.jaxws.doranco.fr/EtudiantService/getEtudiantsResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.jaxws.doranco.fr/EtudiantService/getEtudiants/Fault/Exception")
    })
    public List<Etudiant> getEtudiants()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns fr.doranco.jaxws.soap.service.Etudiant
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEtudiant", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.AddEtudiant")
    @ResponseWrapper(localName = "addEtudiantResponse", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.AddEtudiantResponse")
    @Action(input = "http://service.jaxws.doranco.fr/EtudiantService/addEtudiantRequest", output = "http://service.jaxws.doranco.fr/EtudiantService/addEtudiantResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.jaxws.doranco.fr/EtudiantService/addEtudiant/Fault/Exception")
    })
    public Etudiant addEtudiant(
        @WebParam(name = "arg0", targetNamespace = "")
        Etudiant arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns fr.doranco.jaxws.soap.service.Etudiant
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtudiantById", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.GetEtudiantById")
    @ResponseWrapper(localName = "getEtudiantByIdResponse", targetNamespace = "http://service.jaxws.doranco.fr/", className = "fr.doranco.jaxws.soap.service.GetEtudiantByIdResponse")
    @Action(input = "http://service.jaxws.doranco.fr/EtudiantService/getEtudiantByIdRequest", output = "http://service.jaxws.doranco.fr/EtudiantService/getEtudiantByIdResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.jaxws.doranco.fr/EtudiantService/getEtudiantById/Fault/Exception")
    })
    public Etudiant getEtudiantById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0)
        throws Exception_Exception
    ;

}
